# ------------------------------------------------------------------------------
# Data generated by Félix P Leiva (e-mail: felixpleiva@gmail.com)
# Script created by Félix P Leiva (e-mail: felixpleiva@gmail.com)
# ------------------------------------------------------------------------------
# When using the data or code from this manuscript, please cite it as:

#Leiva FP, Boerrigter JGJ & Verberk WCEP. (2022). The role of cell size in
#shaping responses to oxygen and temperature in fruit flies (1.0). Zenodo.
#https://doi.org/10.5281/zenodo.5949049.
#------------------------------------------------------------------------------
#Cleaning working space
rm(list=ls())
today<-format(Sys.Date(),"%Y%m%d")
# ------------------------------------------------------------------------------
# set the working directory to the folder containing this script:
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

# check directory
getwd()
# ------------------------------------------------------------------------------
# #Libraries
library(lme4)
library(dplyr)
library(car)
library(visreg)
library(AICcmodavg)
# ------------------------------------------------------------------------------
# create a folder for the outputs produced by running this script (if it doesn't
# already exist)
if (!file.exists("../Outputs")) dir.create("../Outputs")
# '../' goes up one level from the current working directory, so this creates
# the 'Outputs' folder just outside the 'R' folder
# ------------------------------------------------------------------------------
# load data
dat<-read.csv("../Outputs/1.1.1. Data to fit the models.csv")
# ------------------------------------------------------------------------------
# See data structure and transform if necessary
str(dat)
dat$sex<-as.factor(dat$sex)
################################################################################
# Does cell size category affect temperature-and-oxygen dependence of body size
# related traits?
################################################################################
# body mass
m1<-lmer(fresh_mass_log ~ temperature + sex + (1|stock),REML = FALSE, data=dat)
m2<-lmer(fresh_mass_log ~ oxygen + sex + (1|stock),REML = FALSE, data=dat)
m3<-lmer(fresh_mass_log ~ temperature + oxygen +  sex + (1|stock),REML = FALSE, data=dat)
m4<-lmer(fresh_mass_log ~ temperature * oxygen +  sex + (1|stock),REML = FALSE, data=dat)
m5<-lmer(fresh_mass_log ~ temperature * oxygen * cell_area_cat +  sex + (1|stock),REML = FALSE, data=dat)
m6<-lmer(fresh_mass_log ~ temperature * cell_area_cat +  sex + (1|stock),REML = FALSE, data=dat)
m7<-lmer(fresh_mass_log ~ oxygen * cell_area_cat +  sex + (1|stock),REML = FALSE, data=dat)

# wing area
w1<-lmer(wing_area_log ~ temperature + sex + (1|stock),REML = FALSE, data=dat)
w2<-lmer(wing_area_log ~ oxygen + sex + (1|stock),REML = FALSE, data=dat)
w3<-lmer(wing_area_log ~ temperature + oxygen +  sex + (1|stock),REML = FALSE, data=dat)
w4<-lmer(wing_area_log ~ temperature * oxygen +  sex + (1|stock),REML = FALSE, data=dat)
w5<-lmer(wing_area_log ~ temperature * oxygen * cell_area_cat +  sex + (1|stock),REML = FALSE, data=dat)
w6<-lmer(wing_area_log ~ temperature * cell_area_cat +  sex + (1|stock),REML = FALSE, data=dat)
w7<-lmer(wing_area_log ~ oxygen * cell_area_cat +  sex + (1|stock),REML = FALSE, data=dat)

# cell area
c1<-lmer(cell_area_log ~ temperature + sex + (1|stock),REML = FALSE, data=dat)
c2<-lmer(cell_area_log ~ oxygen + sex + (1|stock),REML = FALSE, data=dat)
c3<-lmer(cell_area_log ~ temperature + oxygen +  sex + (1|stock),REML = FALSE, data=dat)
c4<-lmer(cell_area_log ~ temperature * oxygen +  sex + (1|stock),REML = FALSE, data=dat)
c5<-lmer(cell_area_log ~ temperature * oxygen * cell_area_cat +  sex + (1|stock),REML = FALSE, data=dat)
c6<-lmer(cell_area_log ~ temperature * cell_area_cat +  sex + (1|stock),REML = FALSE, data=dat)
c7<-lmer(cell_area_log ~ oxygen * cell_area_cat +  sex + (1|stock),REML = FALSE, data=dat)

#-------------------------------------------------------------------------------
#Table 1
#-------------------------------------------------------------------------------
# Body mass
fit.list.table.1.m <- list(m1,m2,m3,m4,m5,m6,m7)

fit.names.table.1.m <-c("temp + sex",
                      "O2 + sex",  
                      "temp + O2 + sex",
                      "temp * O2 + sex",
                      "temp * O2 * CScat + sex",
                      "temp * CScat + sex",
                      "O2 * CScat + sex"
)

#compare by using AICc
fit.table.1.m<-aictab(fit.list.table.1.m,fit.names.table.1.m, second.ord = T,sort = TRUE, digits = 3, LL=TRUE)
fit.table.1.m

# Wing area
fit.list.table.1.w <- list(w1,w2,w3,w4,w5,w6,w7)

fit.names.table.1.w <-c("temp + sex",
                        "O2 + sex",  
                        "temp + O2 + sex",
                        "temp * O2 + sex",
                        "temp * O2 * CScat + sex",
                        "temp * CScat + sex",
                        "O2 * CScat + sex"
)

#compare by using AICc
fit.table.1.w<-aictab(fit.list.table.1.w,fit.names.table.1.w, second.ord = T,sort = TRUE, digits = 3, LL=TRUE)
fit.table.1.w

# Cell area
fit.list.table.1.c <- list(c1,c2,c3,c4,c5,c6,c7)

fit.names.table.1.c <-c("temp + sex",
                        "O2 + sex",  
                        "temp + O2 + sex",
                        "temp * O2 + sex",
                        "temp * O2 * CScat + sex",
                        "temp * CScat + sex",
                        "O2 * CScat + sex"
)

#compare by using AICc
fit.table.1.c<-aictab(fit.list.table.1.c,fit.names.table.1.c, second.ord = T,sort = TRUE, digits = 3, LL=TRUE)
fit.table.1.c


setwd("../Outputs/")#Set directory


# Export tables to .csv
write.csv(fit.table.1.m,"2.3.1. Table_1_Model_comparison_for_body_mass.csv",row.names = FALSE)
write.csv(fit.table.1.w,"2.3.2. Table_1_Model_comparison_for_wing_area.csv",row.names = FALSE)
write.csv(fit.table.1.c,"2.3.3. Table_1_Model_comparison_for_cell_area.csv",row.names = FALSE)

################################################################################
# Figure 2
################################################################################
{
pdf("2.2.1. Figure 2.pdf",width = 7,height = 10,useDingbats = FALSE)
#png("2.2.1. Figure 2.png",width = 7,height = 10,units = "in",res = 600)
par(mfrow=c(3,2),tcl=-0.4, family="serif",omi=c(0,0,0,0.1))
#-------------------------------------------------------------------------------
#Fresh mass
par(mai=c(0.85,0.82,0,0))
visreg(m5,'temperature', by='cell_area_cat',cond = list(oxygen=10),
           print.cond=TRUE,overlay=TRUE,jitter=0.1,legend = FALSE,
           points=list(col=c('#B8860B70', '#6495ED70','#B2ABD270'),cex=1.5,pch=16),
           line=list(col=c('#B8860B', '#6495ED','#B2ABD2'),lwd=4),
           xlab="Temperature (°C)", 
           ylab=expression(paste(log[10],"[fresh mass (mg)]")),
           ylim=c(-0.4,0.1),xlim=c(14,28),
           cex.axis=1.2,cex.lab=1.4)

# Add a legend
legend("top", legend=c("Hypoxia (10 kPa)"), cex=1.4,bty="n")
legend("bottomleft", legend=c("large", "medium","small"),
       lty = c(1,1,1),lwd=3,bty="n",cex=1.2, 
       col=c('#B8860B', '#6495ED','#B2ABD2'))


par(mai=c(0.85,0.82,0,0))
visreg(m5,'temperature', by='cell_area_cat',cond = list(oxygen=21),
       print.cond=TRUE,overlay=TRUE,jitter=0.1,legend = FALSE,
       points=list(col=c('#B8860B70', '#6495ED70','#B2ABD270'),cex=1.5,pch=16),
       line=list(col=c('#B8860B', '#6495ED','#B2ABD2'),lwd=4),
       xlab="Temperature (°C)", 
       ylab=expression(paste(log[10],"[fresh mass (mg)]")),
       ylim=c(-0.4,0.1),xlim=c(14,28),
       cex.axis=1.2,cex.lab=1.4)

# Add a legend
legend("top", legend=c("Normoxia (21 kPa)"), cex=1.4,bty="n")
legend("bottomleft", legend=c("large", "medium","small"),
       lty = c(1,1,1),lwd=3,bty="n",cex=1.2, 
       col=c('#B8860B', '#6495ED','#B2ABD2'))
#-------------------------------------------------------------------------------
#Wing area

par(mai=c(0.85,0.82,0,0))
visreg(w5,'temperature', by='cell_area_cat',cond = list(oxygen=10),
       print.cond=TRUE,overlay=TRUE,jitter=0.1,legend = FALSE,
       points=list(col=c('#B8860B70', '#6495ED70','#B2ABD270'),cex=1.5,pch=16),
       line=list(col=c('#B8860B', '#6495ED','#B2ABD2'),lwd=4),
       xlab="Temperature (°C)", 
       ylab=expression(paste(log[10], "[wing area (",mu, m^2,")]")),
       ylim=c(5.7,6.2),xlim=c(14,28),
       cex.axis=1.2,cex.lab=1.4)

# Add a legend
legend("top", legend=c("Hypoxia (10 kPa)"), cex=1.4,bty="n")
legend("bottomleft", legend=c("large", "medium","small"),
       lty = c(1,1,1),lwd=3,bty="n",cex=1.2, 
       col=c('#B8860B', '#6495ED','#B2ABD2'))


par(mai=c(0.85,0.85,0,0))
visreg(w5,'temperature', by='cell_area_cat',cond = list(oxygen=21),
       print.cond=TRUE,overlay=TRUE,jitter=0.1,legend = FALSE,
       points=list(col=c('#B8860B70', '#6495ED70','#B2ABD270'),cex=1.5,pch=16),
       line=list(col=c('#B8860B', '#6495ED','#B2ABD2'),lwd=4),
       xlab="Temperature (°C)", 
       ylab=expression(paste(log[10], "[wing area (",mu, m^2,")]")),
       ylim=c(5.7,6.2),xlim=c(14,28),
       cex.axis=1.2,cex.lab=1.4)

# Add a legend
legend("top", legend=c("Normoxia (21 kPa)"), cex=1.4,bty="n")
legend("bottomleft", legend=c("large", "medium","small"),
       lty = c(1,1,1),lwd=3,bty="n",cex=1.2, 
       col=c('#B8860B', '#6495ED','#B2ABD2'))
#-------------------------------------------------------------------------------
#Cell area

par(mai=c(0.85,0.82,0,0))
visreg(c5,'temperature', by='cell_area_cat',cond = list(oxygen=10),
       print.cond=TRUE,overlay=TRUE,jitter=0.1,legend = FALSE,
       points=list(col=c('#B8860B70', '#6495ED70','#B2ABD270'),cex=1.5,pch=16),
       line=list(col=c('#B8860B', '#6495ED','#B2ABD2'),lwd=4),
       xlab="Temperature (°C)", 
       ylab=expression(paste(log[10], "[cell area (",mu, m^2,")]")),
       ylim=c(1.9,2.4),xlim=c(14,28),
       cex.axis=1.2,cex.lab=1.4)

# Add a legend
legend("top", legend=c("Hypoxia (10 kPa)"), cex=1.4,bty="n")
legend("bottomleft", legend=c("large", "medium","small"),
       lty = c(1,1,1),lwd=3,bty="n",cex=1.2, 
       col=c('#B8860B', '#6495ED','#B2ABD2'))


par(mai=c(0.85,0.82,0,0))
visreg(c5,'temperature', by='cell_area_cat',cond = list(oxygen=21),
       print.cond=TRUE,overlay=TRUE,jitter=0.1,legend = FALSE,
       points=list(col=c('#B8860B70', '#6495ED70','#B2ABD270'),cex=1.5,pch=16),
       line=list(col=c('#B8860B', '#6495ED','#B2ABD2'),lwd=4),
       xlab="Temperature (°C)", 
       ylab=expression(paste(log[10], "[cell area (",mu, m^2,")]")),
       ylim=c(1.9,2.4),xlim=c(14,28),
       cex.axis=1.2,cex.lab=1.4)

# Add a legend
legend("top", legend=c("Normoxia (21 kPa)"), cex=1.4,bty="n")
legend("bottomleft", legend=c("large", "medium","small"),
       lty = c(1,1,1),lwd=3,bty="n",cex=1.2, 
       col=c('#B8860B', '#6495ED','#B2ABD2'))
dev.off()
}
# ------------------------------------------------------------------------------
# saving session information with all packages versions for reproducibility purposes
sink("../Outputs/2.1.1. Data analyses_Table_1_and_Figure_2_R_session.txt")
sessionInfo()
sink()
# ------------------------------------------------------------------------------
################################################################################
############################ END OF SCRIPT #####################################
################################################################################