# ------------------------------------------------------------------------------
# Data generated by Félix P Leiva, Radboud University (e-mail: felixpleiva@gmail.com)
# Script created by Félix P Leiva, Radboud University (e-mail: felixpleiva@gmail.com)
# ------------------------------------------------------------------------------
# Cite as:

#Leiva FP, Boerrigter JGJ & Verberk WCEP. (2022). Draft version of paper data
#and code of manuscript: The role of cell size in shaping responses to oxygen
#and temperature in fruit flies (1.0). Zenodo.
#https://doi.org/10.5281/zenodo.5949049.
# ------------------------------------------------------------------------------
# Cleaning working space
rm(list=ls())
today<-format(Sys.Date(),"%Y%m%d")
# ------------------------------------------------------------------------------
# set working directory
setwd("C:/Users/Invunche/Dropbox/GitHub/Plastic_responses_DGRP_lines/Outputs")
# check directory
getwd()
# ------------------------------------------------------------------------------
#Libraries
library(lme4)
library(car)
library(visreg)
library(AICcmodavg)
# ------------------------------------------------------------------------------
# load data
dat<-read.csv("1.1.1. Data to fit the models.csv")
# ------------------------------------------------------------------------------
# filter by sex
female=subset(dat,sex!="male")
male=subset(dat,sex=="male")
# ------------------------------------------------------------------------------
################################################################################
#Question 2: Does cell size affect temperature-and-oxygen dependence of body size
#changes in D. melanogaster?
################################################################################
p1<-lmer(fresh_mass_delta ~ temperature + (1|stock),REML = FALSE, data=dat)

p2<-lmer(fresh_mass_delta ~ oxygen + (1|stock),REML = FALSE, data=dat)

p3<-lmer(fresh_mass_delta ~ temperature * oxygen + (1|stock),REML = FALSE, data=dat)

p4<-lmer(fresh_mass_delta ~ temperature * cell_area_delta + (1|stock),REML = FALSE, data=dat)

p5<-lmer(fresh_mass_delta ~ oxygen * cell_area_delta + (1|stock),REML = FALSE, data=dat)

p6<-lmer(fresh_mass_delta ~ temperature * oxygen * cell_area_delta + (1|stock),REML = FALSE, data=dat)

fit.list.table.3 <- list(p1,p2,p3,p4,p5,p6)

fit.names.table.3 <-c("temperature",
                      "oxygen",  
                      "temperature * oxygen",
                      "temperature * cell_area_delta",
                      "oxygen * cell_area_delta",
                      "temperature * oxygen * cell_area_delta"
)

#compare by using AICc
fit.table.3<-aictab(fit.list.table.3,fit.names.table.3, second.ord = T,sort = TRUE, digits = 3, LL=TRUE)
fit.table.3


# Model selection based on AICc:
#     
#                                         K    AICc Delta_AICc AICcWt Cum.Wt       LL
# temperature * oxygen * cell_area_delta 10 3105.45       0.00   0.91   0.91 -1542.47
# temperature * oxygen                    6 3110.12       4.67   0.09   1.00 -1548.96
# oxygen * cell_area_delta                6 3144.82      39.37   0.00   1.00 -1566.31
# temperature * cell_area_delta           6 3188.46      83.01   0.00   1.00 -1588.13
# oxygen                                  4 3237.94     132.49   0.00   1.00 -1614.92
# temperature                             4 3318.51     213.06   0.00   1.00 -1655.21

# export Table
write.csv(fit.table.3,"4.3.1. Table 3 Model comparision cell size contribution to changes in body mass.csv",row.names = FALSE)
summary(p6) #Table 4

# Fixed effects:
#                                     Estimate Std. Error t value
# (Intercept)                        22.902311  10.668778   2.147
# temperature                        -1.902992   0.513893  -3.703
# oxygen                             -0.841737   0.640716  -1.314
# cell_area_delta                    -1.327463   0.872976  -1.521
# temperature:oxygen                  0.078092   0.029734   2.626
# temperature:cell_area_delta         0.080817   0.045398   1.780
# oxygen:cell_area_delta              0.023594   0.052361   0.451
# temperature:oxygen:cell_area_delta -0.001860   0.002705  -0.688

Anova(p6)
# Response: fresh_mass_delta
#                                       Chisq Df Pr(>Chisq)    
# temperature                        16.2441  1  5.568e-05 ***
# oxygen                             72.9192  1  < 2.2e-16 ***
# cell_area_delta                     0.5616  1  0.4536100    
# temperature:oxygen                  7.0285  1  0.0080224 ** 
# temperature:cell_area_delta        11.1069  1  0.0008601 ***
# oxygen:cell_area_delta              1.5716  1  0.2099697    
# temperature:oxygen:cell_area_delta  0.4727  1  0.4917409

################################################################################
# Figure 5
################################################################################
{
pdf("4.2.3. Figure 5.pdf",width = 10,height = 5,useDingbats = FALSE)
#png("4.2.3. Figure 5.png",width = 10,height = 5,units = "in",res = 300)
par(mfrow=c(1,2),tcl=-0.4, family="serif",omi=c(0,0,0,0))

# under hypoxia
par(mai=c(0.82,0.82,0.2,0.2))
visreg(p6,"cell_area_delta",by="temperature",cond=list(oxygen=10),overlay=TRUE,
   print.cond=TRUE,legend = FALSE,
       points=list(col=c("#2c7fb870", "#de2d2670"),pch=16,cex=1.4),
       line=list(col=c("#2c7fb8", "#de2d26"), lwd=4),
       xlab="Standardised cell area (%)", ylab="Standardised fresh mass (%)",
       ylim=c(-50,50),xlim=c(-50,50),
       xaxs = "i",yaxs = "i",#force origin of our x- and y-axes
       cex.axis=1.5,cex.lab=1.5)
abline(h=0,lty=2,lwd=2)
abline(v=0,lty=2,lwd=2)
## Draw a polygon defining an area on the graph
xx = c(-49.8,-49.8,49.8,49.8)
yy = c(35,49.8,49.8,35)
polygon(xx,yy, col = 'grey90', border = NA)
legend("bottomright", legend=c("17°C", "25°C"),
       lty = 1,lwd=4, bty="n",
       col=c("#2c7fb8", "#de2d26"),cex=1.4)
text(0,42.5,"hypoxic-developed flies",font=2,cex=1.5)

# under normoxia
par(mai=c(0.82,0.82,0.2,0.2))
visreg(p6,"cell_area_delta",by="temperature",cond=list(oxygen=21),overlay=TRUE,
       print.cond=TRUE,legend = FALSE,
       points=list(col=c("#2c7fb870", "#de2d2670"),pch=16,cex=1.4),
       line=list(col=c("#2c7fb8", "#de2d26"), lwd=4),
       xlab="Standardised cell area (%)", ylab="Standardised fresh mass (%)",
       ylim=c(-50,50),xlim=c(-50,50),
       xaxs = "i",yaxs = "i",#force origin of our x- and y-axes
       cex.axis=1.5,cex.lab=1.5)
abline(h=0,lty=2,lwd=2)
abline(v=0,lty=2,lwd=2)
## Draw a polygon defining an area on the graph
xx = c(-49.8,-49.8,49.8,49.8)
yy = c(35,49.8,49.8,35)
polygon(xx,yy, col = 'grey90', border = NA)
legend("bottomright", legend=c("17°C", "25°C"),
       lty = 1,lwd=4, bty="n",
       col=c("#2c7fb8", "#de2d26"),cex=1.4)
text(0,42.5,"normoxic-developed flies",font=2,cex=1.5)

dev.off()
}
# ------------------------------------------------------------------------------
# saving session information with all packages versions for reproducibility purposes
sink("C:/Users/Invunche/Dropbox/GitHub/Plastic_responses_DGRP_lines/Outputs/4.1.1. Data analyses_Tables_3_4_and_Figure_5_R_session.txt")
sessionInfo()
sink()
# ------------------------------------------------------------------------------
################################################################################
############################ END OF SCRIPT #####################################
################################################################################
